export const SET_LOCALIDADES = 'SET_LOCALIDADES';
export const SET_LOCALIDADE = 'SET_LOCALIDADE';
export const SET_LOCALIDADE_METADATA = 'SET_LOCALIDADE_METADATA';
export const GET_LOCALIDADE_METADATA = 'GET_LOCALIDADE_METADATA';
export const UPDATE_LOCALIDADE = 'UPDATE_LOCALIDADE';

