# Generated by Django 2.2.2 on 2019-06-05 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadroesPlantio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('padrao', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('escala', models.IntegerField(blank=True, default=10, verbose_name='escala')),
                ('tipo', models.CharField(choices=[('RE', 'Repetição'), ('PE', 'Personalidado')], default='RE', max_length=2, verbose_name='tipo_cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(blank=True, choices=[('CA', 'Canteiro'), ('MA', 'Mandala'), ('PD', 'Plantio direto')], max_length=2, verbose_name='tipo_cultivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manejo.PadroesPlantio')),
            ],
        ),
    ]
