# Generated by Django 2.2.2 on 2019-06-05 13:34

from django.db import migrations, models
import django.db.models.deletion
import especie.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familia', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(blank=True, max_length=255, verbose_name='nome_cientifico')),
                ('nomes_populares', models.CharField(max_length=1000, verbose_name='nomes_populares')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('temperatura_min', models.IntegerField(blank=True, null=True, verbose_name='temperatura_min')),
                ('temperatura_max', models.IntegerField(blank=True, null=True, verbose_name='temperatura_max')),
                ('porte', models.CharField(blank=True, choices=[('Aquática', 'Aquática'), ('Erva pequena', 'Erva pequena'), ('Erva média', 'Erva média'), ('Erva grande', 'Erva grande'), ('Trepadeira', 'Trepadeira'), ('Arbusto', 'Arbusto'), ('Árvore pequena', 'Árvore pequena'), ('Árvore média', 'Árvore média'), ('Árvore grande', 'Árvore grande'), ('Outro / não especificado', 'Outro / não especificado')], max_length=30, verbose_name='porte')),
                ('tempo_vida', models.IntegerField(blank=True, null=True, verbose_name='tempo_vida')),
                ('unidade_tempo_vida', models.CharField(choices=[('D', 'Dias'), ('M', 'Meses'), ('A', 'Anos')], default='M', max_length=1, verbose_name='unidade_tempo_vida')),
                ('umidade', models.CharField(blank=True, choices=[('Ultra seco', 'Ultra seco'), ('Seco', 'Seco'), ('Moderado', 'Moderado'), ('Úmido', 'Úmido'), ('Ultra úmido', 'Ultra úmido')], max_length=30, verbose_name='umidade')),
                ('exigencia_solo', models.CharField(blank=True, choices=[('Arenoso', 'Arenoso'), ('Areno-siltoso', 'Areno-siltoso'), ('Siltoso', 'Siltoso'), ('Argiloso', 'Argiloso'), ('Argilo-siltoso', 'Argilo-siltoso'), ('AE', 'Areno-argiloso'), ('Rochoso', 'Rochoso'), ('Húmico', 'Húmico'), ('Outros', 'Outros')], max_length=30, verbose_name='exigencia_solo')),
                ('tolerancia_poda', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='tolerancia_poda')),
                ('exigencia_sol', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='exigencia_sol')),
                ('inicio_colheita', models.CharField(blank=True, max_length=5, verbose_name='inicio_colheita')),
                ('estrato', models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto/dossel', 'Alto/dossel'), ('Emergente', 'Emergente')], max_length=30, verbose_name='estrato')),
                ('sucessao', models.CharField(blank=True, choices=[('Colonizadora', 'Colonizadora'), ('Pioneiras', 'Pioneiras'), ('Secundárias iniciais', 'Secundárias iniciais'), ('Secundárias tardias', 'Secundárias tardias'), ('Clímax', 'Clímax')], max_length=30, verbose_name='sucessao')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=especie.models.get_image_path)),
                ('formas_plantio', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('semente', 'semente'), ('muda', 'muda'), ('estaca', 'estaca'), ('rama', 'rama'), ('tubérculo', 'tubérculo')], max_length=30, verbose_name='formas_plantio')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familia.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('exigencia_solo', models.CharField(blank=True, choices=[('Arenoso', 'Arenoso'), ('Areno-siltoso', 'Areno-siltoso'), ('Siltoso', 'Siltoso'), ('Argiloso', 'Argiloso'), ('Argilo-siltoso', 'Argilo-siltoso'), ('AE', 'Areno-argiloso'), ('Rochoso', 'Rochoso'), ('Húmico', 'Húmico'), ('Outros', 'Outros')], max_length=30, verbose_name='exigencia_solo')),
                ('tolerancia_poda', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='tolerancia_poda')),
                ('exigencia_sol', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='exigencia_sol')),
                ('inicio_colheita', models.CharField(blank=True, max_length=5, verbose_name='inicio_colheita')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especie.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interacao', models.CharField(blank=True, choices=[('Sinergia', 'Sinergia'), ('Alelopatia mútua', 'Alelopatia mútua'), ('Alelopatia própria', 'Alelopatia própria'), ('Alelopatia alheia', 'Alelopatia alheia')], max_length=10, verbose_name='tipo_interacao')),
                ('intensidade', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='intensidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('especie_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especie_a', to='especie.Especie')),
                ('especie_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especie_b', to='especie.Especie')),
                ('familia_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familia_a', to='familia.Familia')),
                ('familia_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familia_b', to='familia.Familia')),
            ],
        ),
    ]
