# Generated by Django 2.2.2 on 2019-06-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='tolerancia_poda',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='tolerancia_poda'),
        ),
    ]
