# Generated by Django 2.2.2 on 2019-06-11 02:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0002_auto_20190610_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='estrato',
            field=models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto/dossel', 'Alto/dossel'), ('Emergente', 'Emergente')], max_length=30, null=True, verbose_name='estrato'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='exigencia_sol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='exigencia_sol'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='formas_plantio',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('semente', 'semente'), ('muda', 'muda'), ('estaca', 'estaca'), ('rama', 'rama'), ('tubérculo', 'tubérculo')], max_length=30, null=True, verbose_name='formas_plantio'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='inicio_colheita',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='inicio_colheita'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='sucessao',
            field=models.CharField(blank=True, choices=[('Colonizadora', 'Colonizadora'), ('Pioneiras', 'Pioneiras'), ('Secundárias iniciais', 'Secundárias iniciais'), ('Secundárias tardias', 'Secundárias tardias'), ('Clímax', 'Clímax')], max_length=30, null=True, verbose_name='sucessao'),
        ),
    ]
