# Generated by Django 3.0.4 on 2020-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0003_auto_20190610_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='tipo_interacao',
            field=models.CharField(blank=True, choices=[('Sinergia', 'Sinergia'), ('Alelopatia mútua', 'Alelopatia mútua'), ('Alelopatia própria', 'Alelopatia própria'), ('Alelopatia alheia', 'Alelopatia alheia')], max_length=18, verbose_name='tipo_interacao'),
        ),
    ]
