version: '3'

services:
  db:
    image: postgres
    volumes:
      - /data/postgresql_data/:/var/lib/postgresql/data/
    networks:
      - plantio
  
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - django
    networks:
      - plantio
  
  django:
    build: ./app
    volumes:
      - ./app/:/app/
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    networks:
      - plantio
      
networks:
  plantio:
    driver: bridge
