# Generated by Django 2.2.2 on 2019-06-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especie', '__first__'),
        ('area', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField(verbose_name='data_plantio')),
                ('dimensao', models.FloatField(blank=True, verbose_name='dimensao')),
                ('unidade_medida', models.CharField(choices=[('m', 'metro'), ('un', 'unidade'), ('a', 'area')], max_length=10, verbose_name='unidade_medida')),
                ('espacamento', models.CharField(blank=True, max_length=50, verbose_name='espacamento')),
                ('densidade', models.CharField(blank=True, max_length=50, verbose_name='densidade')),
                ('estado', models.CharField(choices=[('planejado', 'planejado'), ('plantado', 'plantado'), ('finalizado/removido', 'finalizado/removido')], max_length=20, verbose_name='unidade_medida')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especie.Especie')),
            ],
        ),
    ]
