# Generated by Django 2.2.2 on 2019-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='unidade_medida',
            field=models.CharField(choices=[('planejado', 'planejado'), ('plantado', 'plantado'), ('finalizado/removido', 'finalizado/removido')], max_length=10, verbose_name='unidade_medida'),
        ),
    ]
