# Generated by Django 2.2.2 on 2019-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0003_auto_20190607_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='unidade_medida',
            field=models.CharField(choices=[('m', 'metro'), ('un', 'unidade'), ('a', 'area')], max_length=10, verbose_name='unidade_medida'),
        ),
    ]
