# Generated by Django 2.2.2 on 2019-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0004_auto_20190607_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='estado',
            field=models.CharField(choices=[('planejado', 'planejado'), ('plantado', 'plantado'), ('finalizado/removido', 'finalizado/removido')], default='planejado', max_length=20, verbose_name='estado'),
        ),
    ]
