# Generated by Django 2.2.2 on 2019-06-05 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('matriz_porte', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('floracao', models.BooleanField(default=False, verbose_name='floracao')),
                ('frutificacao', models.BooleanField(default=False, verbose_name='frutificacao')),
                ('deciduidade', models.BooleanField(default=False, verbose_name='deciduidade')),
                ('inicio', models.CharField(blank=True, max_length=5, verbose_name='inicio_fase')),
                ('fim', models.CharField(blank=True, max_length=5, verbose_name='fim_fase')),
                ('posicao', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='posicao')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especie', to='especie.Especie')),
                ('fases', models.ManyToManyField(default=False, related_name='Fase', to='ciclo.Fase')),
            ],
        ),
    ]
