export const SET_ESPECIES = 'SET_ESPECIES';
export const SET_ESPECIE = 'SET_ESPECIE';
export const SET_ESPECIE_METADATA = 'SET_ESPECIE_METADATA';
export const GET_ESPECIE_METADATA = 'GET_ESPECIE_METADATA';
export const UPDATE_ESPECIE = 'UPDATE_ESPECIE';
