# Generated by Django 2.2.2 on 2019-06-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('bioma', models.CharField(blank=True, choices=[('Cerrado', 'Cerrado'), ('Mata atlântica', 'Mata atlântica'), ('Floresta estacional semi decidual', 'Floresta estacional semi decidual'), ('Pampa', 'Pampa'), ('Amazônico', 'Amazônico'), ('Pantanal', 'Pantanal')], max_length=255, verbose_name='bioma')),
                ('clima', models.CharField(blank=True, choices=[('Tropical úmido', 'Tropical úmido'), ('Tropical seco', 'Tropical seco'), ('Sub tropical seco', 'Sub tropical seco'), ('Sub tropical úmido', 'Sub tropical úmido'), ('Temperado úmido', 'Temperado úmido'), ('Temperado seco', 'Temperado seco')], max_length=255, verbose_name='clima')),
                ('cidade', models.CharField(blank=True, max_length=255, verbose_name='cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('dimensao', models.FloatField(blank=True, verbose_name='dimensao')),
                ('largura', models.FloatField(blank=True, default=0, verbose_name='largura')),
                ('comprimento', models.FloatField(blank=True, default=0, verbose_name='comprimento')),
                ('solo_predominante', models.TextField(blank=True, choices=[('Arenoso', 'Arenoso'), ('Areno-siltoso', 'Areno-siltoso'), ('Siltoso', 'Siltoso'), ('Argiloso', 'Argiloso'), ('Argilo-siltoso', 'Argilo-siltoso'), ('AE', 'Areno-argiloso'), ('Rochoso', 'Rochoso'), ('Húmico', 'Húmico'), ('Outros', 'Outros')], verbose_name='solo predominante')),
                ('declividade_predominante', models.TextField(blank=True, choices=[('Plano', 'Plano'), ('Baixada', 'Baixada'), ('Encosta acentuada', 'Encosta acentuada'), ('Encosta suave', 'Encosta suave')], verbose_name='declividade predominante')),
                ('microclima', models.TextField(blank=True, choices=[('Campo aberto', 'Campo aberto'), ('Capoeira rala', 'Capoeira rala'), ('Capoeira densa', 'Capoeira densa'), ('Mata fechada', 'Mata fechada'), ('Chapada', 'Chapada'), ('Grota', 'Grota'), ('Baixada', 'Baixada'), ('Topo de morro', 'Topo de morro')], null=True, verbose_name='microclima')),
                ('localidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Localidade')),
            ],
        ),
    ]
